# Generated by Django 3.0.4 on 2020-03-31 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=220)),
                ('post_description', models.CharField(max_length=220)),
                ('post_body', models.TextField()),
                ('post_links', models.URLField()),
                ('post_images', models.ImageField(upload_to='images/')),
                ('post_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
