# Generated by Django 3.0.4 on 2020-03-31 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-post_date']},
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='post_body',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='post_description',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='post_images',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='post_links',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='post_title',
        ),
        migrations.AddField(
            model_name='posts',
            name='slug',
            field=models.SlugField(default='', max_length=220, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0),
        ),
        migrations.AddField(
            model_name='posts',
            name='title',
            field=models.CharField(default='', max_length=220, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
